package org.devnull.matchmaking.statistics;

import org.devnull.matchmaking.Match;
import org.devnull.matchmaking.MatchStatistics;

import java.util.Set;

public class BasicMatchStatistics implements MatchStatistics, java.io.Serializable {

    /** Generated by the serialver utility */
    //TODO: public static final long serialVersionUID = 417360850570173236L;



    public final Match match;
    public final double winRateTeam1Min;
    public final double winRateTeam1Max;
    public final double winRateTeam2Min;
    public final double winRateTeam2Max;
    public final double winRateMatchMin;
    public final double winRateMatchMax;
    public final long battlesFoughtTeam1Min;
    public final long battlesFoughtTeam1Max;
    public final long battlesFoughtTeam2Min;
    public final long battlesFoughtTeam2Max;
    public final long battlesFoughtMatchMin;
    public final long battlesFoughtMatchMax;

    public BasicMatchStatistics(
            final Match match,
            final double winRateTeam1Min,
            final double winRateTeam1Max,
            final double winRateTeam2Min,
            final double winRateTeam2Max,
            final double winRateMatchMin,
            final double winRateMatchMax,
            final long battlesFoughtTeam1Min,
            final long battlesFoughtTeam1Max,
            final long battlesFoughtTeam2Min,
            final long battlesFoughtTeam2Max,
            final long battlesFoughtMatchMin,
            final long battlesFoughtMatchMax
    ) {
        this.match = match;
        this.winRateTeam1Min = winRateTeam1Min; 
        this.winRateTeam1Max = winRateTeam1Max; 
        this.winRateTeam2Min = winRateTeam2Min; 
        this.winRateTeam2Max = winRateTeam2Max; 
        this.winRateMatchMin = winRateMatchMin; 
        this.winRateMatchMax = winRateMatchMax; 
        this.battlesFoughtTeam1Min = battlesFoughtTeam1Min; 
        this.battlesFoughtTeam1Max = battlesFoughtTeam1Max; 
        this.battlesFoughtTeam2Min = battlesFoughtTeam2Min; 
        this.battlesFoughtTeam2Max = battlesFoughtTeam2Max; 
        this.battlesFoughtMatchMin = battlesFoughtMatchMin; 
        this.battlesFoughtMatchMax = battlesFoughtMatchMax; 
    }

    @Override
    public Object getStatistics(String key) {
        return null;
    }

}
