package org.devnull.matchmaking;

import java.util.Set;

public class MatchStatistics implements java.io.Serializable {

    /** Generated by the serialver utility */
    //TODO: public static final long serialVersionUID = 417360850570173236L;



    public final Match match;
    public final double winRateTeam1Min;
    public final double winRateTeam1Max;
    public final double winRateTeam2Min;
    public final double winRateTeam2Max;
    public final double winRateMatchMin;
    public final double winRateMatchMax;
    public final long battlesFoughtTeam1Min;
    public final long battlesFoughtTeam1Max;
    public final long battlesFoughtTeam2Min;
    public final long battlesFoughtTeam2Max;
    public final long battlesFoughtMatchMin;
    public final long battlesFoughtMatchMax;

    public MatchStatistics(Match match) {
        this.match = match;
        Set<PlayerInterface> team1 = match.getTeam1();
        Set<PlayerInterface> team2 = match.getTeam2();

        double winRateTeam1Min = Double.MAX_VALUE;
        double winRateTeam1Max = Double.MIN_VALUE;
        double winRateTeam2Min = Double.MAX_VALUE;
        double winRateTeam2Max = Double.MIN_VALUE;
        double winRateMatchMin = Double.MAX_VALUE;
        double winRateMatchMax = Double.MIN_VALUE;
        long battlesFoughtTeam1Min = Long.MAX_VALUE;
        long battlesFoughtTeam1Max = Long.MIN_VALUE;
        long battlesFoughtTeam2Min = Long.MAX_VALUE;
        long battlesFoughtTeam2Max = Long.MIN_VALUE;
        long battlesFoughtMatchMin = Long.MAX_VALUE;
        long battlesFoughtMatchMax = Long.MIN_VALUE;

        for (final PlayerInterface player : team1) {
            //final PlayerToBeMatched player = (PlayerToBeMatched) p;

            double winRate = player.getWinRate();
            if (winRate < winRateTeam1Min) {
                winRateTeam1Min = winRate;
            }
            if (winRate > winRateTeam1Max) {
                winRateTeam1Max = winRate;
            }
            if (winRate < winRateMatchMin) {
                winRateMatchMin = winRate;
            }
            if (winRate > winRateMatchMax) {
                winRateMatchMax = winRate;
            }

            long battlesFought = player.getBattlesFought();
            if (battlesFought < battlesFoughtTeam1Min) {
                battlesFoughtTeam1Min = battlesFought;
            }
            if (battlesFought > battlesFoughtTeam1Max) {
                battlesFoughtTeam1Max = battlesFought;
            }
            if (battlesFought < battlesFoughtMatchMin) {
                battlesFoughtMatchMin = battlesFought;
            }
            if (battlesFought > battlesFoughtMatchMax) {
                battlesFoughtMatchMax = battlesFought;
            }
        }

        for (final PlayerInterface player : team2) {
            //final PlayerToBeMatched player = (PlayerToBeMatched) p;

            double winRate = player.getWinRate();
            if (winRate < winRateTeam2Min) {
                winRateTeam2Min = winRate;
            }
            if (winRate > winRateTeam2Max) {
                winRateTeam2Max = winRate;
            }
            if (winRate < winRateMatchMin) {
                winRateMatchMin = winRate;
            }
            if (winRate > winRateMatchMax) {
                winRateMatchMax = winRate;
            }

            long battlesFought = player.getBattlesFought();
            if (battlesFought < battlesFoughtTeam2Min) {
                battlesFoughtTeam2Min = battlesFought;
            }
            if (battlesFought > battlesFoughtTeam2Max) {
                battlesFoughtTeam2Max = battlesFought;
            }
            if (battlesFought < battlesFoughtMatchMin) {
                battlesFoughtMatchMin = battlesFought;
            }
            if (battlesFought > battlesFoughtMatchMax) {
                battlesFoughtMatchMax = battlesFought;
            }
        }

        this.winRateTeam1Min = winRateTeam1Min; 
        this.winRateTeam1Max = winRateTeam1Max; 
        this.winRateTeam2Min = winRateTeam2Min; 
        this.winRateTeam2Max = winRateTeam2Max; 
        this.winRateMatchMin = winRateMatchMin; 
        this.winRateMatchMax = winRateMatchMax; 
        this.battlesFoughtTeam1Min = battlesFoughtTeam1Min; 
        this.battlesFoughtTeam1Max = battlesFoughtTeam1Max; 
        this.battlesFoughtTeam2Min = battlesFoughtTeam2Min; 
        this.battlesFoughtTeam2Max = battlesFoughtTeam2Max; 
        this.battlesFoughtMatchMin = battlesFoughtMatchMin; 
        this.battlesFoughtMatchMax = battlesFoughtMatchMax; 
    }

}
